"""
run_fusion.py

Wrapper to run the decision_engine on outputs from prediction.py
"""

import pandas as pd
import pickle
import os
import json
from models.decision_engine import run_decision_engine
from models.packet import PacketData, PredictionResult, PacketWithPrediction
from services.email_services import send_attack_alert, alert_system

# Path to the prediction CSV generated by prediction.py
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PREDICTION_CSV = os.path.join(SCRIPT_DIR, "attack_predictions.csv")
OUTPUT_CSV = os.path.join(SCRIPT_DIR, "fusion_results.csv")

def decode_labels(label_encoded_series):
    """
    Decode numeric label indices to attack type names
    Uses the label encoder from the training process
    """
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # Load the label encoders
    with open(os.path.join(BASE_DIR, "Supervised", "labelencoder_xgb.pkl"), "rb") as f:
        xgb_le = pickle.load(f)
    
    with open(os.path.join(BASE_DIR, "Data_cleaning", "labelencoder.pkl"), "rb") as f:
        original_le = pickle.load(f)
    
    # Decode: first get the original numeric labels, then get their text names
    original_labels = original_le.inverse_transform(xgb_le.classes_)
    label_map = {i: original_labels[i] for i in range(len(original_labels))}
    decoded_labels = label_encoded_series.map(label_map)
    return decoded_labels

def main():

    # Load predictions
    results = pd.read_csv(PREDICTION_CSV)
    
    # Labels (already decoded earlier)    
    if "xgb_label" not in results.columns:
        if "predicted_label_encoded" in results.columns:
            results["xgb_label"] = decode_labels(
                results["predicted_label_encoded"]
            )
        else:
            results["xgb_label"] = "Unknown"


    # Scores    
    results.rename(
        columns={"attack_score_unsupervised": "ae_score"},
        inplace=True
    )


    if "ae_score" not in results.columns:
        results["ae_score"] = results["combined_score"]


    # Normalize supervised score
    if "attack_score_supervised" in results.columns:

        mn = results["attack_score_supervised"].min()
        mx = results["attack_score_supervised"].max()
        if mx > mn:
            results["xgb_confidence"] = (
                (results["attack_score_supervised"] - mn) / (mx - mn)
            )
        else:
            results["xgb_confidence"] = 0.5
    else:
        results["xgb_confidence"] = 0.5

    # Decision Engine
    decision_df = run_decision_engine(results)

    metadata_cols = [
    "src_ip", "dst_ip", "protocol",
    "total_packets", "total_bytes",
    "timestamp", "explanation", "predicted_label_encoded"
    ]
    decision_df = decision_df.merge(
    results[metadata_cols],
    left_index=True,
    right_index=True,
    how="left",
    validate="1:1"
    )

    # Save
    decision_df.to_csv(OUTPUT_CSV, index=False)
    print(f"Fusion results saved to: {OUTPUT_CSV}")

    # Summary
    print("\nSummary of attacks detected:")
    print(decision_df["severity"].value_counts())

    # Alerts
    from datetime import datetime as _dt
    sent = 0
    attacks = decision_df[decision_df["attack"] == True]
    for idx, row in attacks.iterrows():
        try:
            pkt = PacketData(
                id=int(idx),
                src_ip=row.get("src_ip", "unknown"),
                dest_ip=row.get("dst_ip", "unknown"),
                #length=(row.get("packet_size", 0)),
                protocol=row.get("protocol", "unknown"),
                timestamp=row.get("timestamp", _dt.utcnow().timestamp())
            )
            pred = PredictionResult(
                label="attack",
                confidence=float(row.get("fusion_score", 0.0)),
                attack_type=row.get("attack_type", "Unknown"),
                explanation={
                    "text": str(row.get("explanation", "No explanation"))
                }
            )
            pw = PacketWithPrediction(packet=pkt, prediction=pred)
            alert_system.log_attack(pw, provided_severity=row.get("severity"))
            ok = send_attack_alert(
                pw,
                provided_severity=row.get("severity"),
                use_email=True
            )
            if ok:
                sent += 1
        except Exception as e:
            print("[Alert Error]", e)
    print(f"Sent alerts for {sent} detected attacks.")

if __name__ == "__main__":
    main()
