"""
run_fusion.py

Wrapper to run the decision_engine on outputs from prediction.py
"""

import pandas as pd
import pickle
import os
from models.decision_engine import run_decision_engine

# Path to the prediction CSV generated by prediction.py
PREDICTION_CSV = "backend/attack_predictions.csv"
OUTPUT_CSV = "backend/fusion_results.csv"

def decode_labels(label_encoded_series):
    """
    Decode numeric label indices to attack type names
    Uses the label encoder from the training process
    """
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # Load the label encoders
    with open(os.path.join(BASE_DIR, r"Supervised\labelencoder_xgb.pkl"), "rb") as f:
        xgb_le = pickle.load(f)
    
    with open(os.path.join(BASE_DIR, r"Data_cleaning\labelencoder.pkl"), "rb") as f:
        original_le = pickle.load(f)
    
    # Decode: first get the original numeric labels, then get their text names
    # xgb_le.classes_ contains [0, 1, 2, 3, 5, 6] which are indices into original_le
    original_labels = original_le.inverse_transform(xgb_le.classes_)
    
    # Create mapping from prediction indices to attack types
    label_map = {i: original_labels[i] for i in range(len(original_labels))}
    
    # Apply mapping
    decoded_labels = label_encoded_series.map(label_map)
    return decoded_labels

def main():
    # Load prediction outputs
    results = pd.read_csv(PREDICTION_CSV)
    
    # Decode numeric labels to attack type names
    if "predicted_label_encoded" in results.columns:
        results["xgb_label"] = decode_labels(results["predicted_label_encoded"])
    else:
        results["xgb_label"] = "Unknown"
    
    # Map columns to expected format by decision_engine
    results.rename(columns={
        "attack_score_unsupervised": "ae_score"
    }, inplace=True)
    
    # Ensure ae_score exists; if not, use combined_score
    if "ae_score" not in results.columns and "combined_score" in results.columns:
        results["ae_score"] = results["combined_score"]
    
    # Convert attack_score_supervised to confidence (normalize to 0-1 range)
    # The supervised score likely represents how anomalous/different the sample is
    # We'll use it as confidence with min-max normalization
    if "attack_score_supervised" in results.columns:
        min_score = results["attack_score_supervised"].min()
        max_score = results["attack_score_supervised"].max()
        # Normalize to 0-1 range
        if max_score > min_score:
            results["xgb_confidence"] = (
                (results["attack_score_supervised"] - min_score) / (max_score - min_score)
            )
        else:
            results["xgb_confidence"] = 0.5
    else:
        results["xgb_confidence"] = 0.5  # Default confidence if not available

    # Run fusion / decision engine
    decision_df = run_decision_engine(results)

    # Save decisions
    decision_df.to_csv(OUTPUT_CSV, index=False)
    print(f"Fusion results saved to: {OUTPUT_CSV}")

    # Optional: show summary
    print("\nSummary of attacks detected:")
    print(decision_df["severity"].value_counts())

if __name__ == "__main__":
    main()
