"""
run_fusion.py

Wrapper to run the decision_engine on outputs from prediction.py
"""

import pandas as pd
import pickle
import os
import json
from models.decision_engine import run_decision_engine
from models.packet import PacketData, PredictionResult, PacketWithPrediction
from services.email_services import send_attack_alert

# Path to the prediction CSV generated by prediction.py
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PREDICTION_CSV = os.path.join(SCRIPT_DIR, "attack_predictions.csv")
OUTPUT_CSV = os.path.join(SCRIPT_DIR, "fusion_results.csv")

def decode_labels(label_encoded_series):
    """
    Decode numeric label indices to attack type names
    Uses the label encoder from the training process
    """
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # Load the label encoders
    with open(os.path.join(BASE_DIR, r"Supervised\labelencoder_xgb.pkl"), "rb") as f:
        xgb_le = pickle.load(f)
    
    with open(os.path.join(BASE_DIR, r"Data_cleaning\labelencoder.pkl"), "rb") as f:
        original_le = pickle.load(f)
    
    # Decode: first get the original numeric labels, then get their text names
    original_labels = original_le.inverse_transform(xgb_le.classes_)
    label_map = {i: original_labels[i] for i in range(len(original_labels))}
    decoded_labels = label_encoded_series.map(label_map)
    return decoded_labels

def main():
    # Load prediction outputs
    results = pd.read_csv(PREDICTION_CSV)
    
    # Decode numeric labels to attack type names
    if "predicted_label_encoded" in results.columns:
        results["xgb_label"] = decode_labels(results["predicted_label_encoded"])
    else:
        results["xgb_label"] = "Unknown"
    
    # Map columns to expected format by decision_engine
    results.rename(columns={"attack_score_unsupervised": "ae_score"}, inplace=True)
    if "ae_score" not in results.columns and "combined_score" in results.columns:
        results["ae_score"] = results["combined_score"]
    
    if "attack_score_supervised" in results.columns:
        min_score = results["attack_score_supervised"].min()
        max_score = results["attack_score_supervised"].max()
        if max_score > min_score:
            results["xgb_confidence"] = (
                (results["attack_score_supervised"] - min_score) / (max_score - min_score)
            )
        else:
            results["xgb_confidence"] = 0.5
    else:
        results["xgb_confidence"] = 0.5

    # Run fusion / decision engine
    decision_df = run_decision_engine(results)

    # Save decisions
    decision_df.to_csv(OUTPUT_CSV, index=False)
    print(f"Fusion results saved to: {OUTPUT_CSV}")

    # Optional: show summary
    print("\nSummary of attacks detected:")
    print(decision_df["severity"].value_counts())

    # Send alerts for detected attacks
    from datetime import datetime as _dt
    sent = 0
    for idx, row in decision_df[decision_df['attack'] == True].iterrows():
        pkt_id = int(idx)
        src_ip = row.get('src_ip', 'unknown') if 'src_ip' in row.index else 'unknown'
        dest_ip = row.get('dest_ip', 'unknown') if 'dest_ip' in row.index else 'unknown'
        protocol = row.get('protocol', 'unknown') if 'protocol' in row.index else 'unknown'
        length = int(row.get('packet_length', 0)) if 'packet_length' in row.index and pd.notna(row.get('packet_length')) else 0
        ts_raw = row.get('timestamp', _dt.utcnow().isoformat())
        try:
            pkt_ts = _dt.fromisoformat(str(ts_raw)).timestamp()
        except Exception:
            try:
                pkt_ts = float(ts_raw)
            except Exception:
                pkt_ts = _dt.utcnow().timestamp()
        conf = float(row.get('fusion_score', row.get('xgb_confidence', 0.0)))
        attack_type = row.get('attack_type', 'Unknown')
        severity = row.get('severity', 'Low')
        try:
            packet = PacketData(id=pkt_id, src_ip=src_ip, dest_ip=dest_ip, length=length, protocol=protocol, timestamp=pkt_ts)
            prediction = PredictionResult(label='attack', confidence=conf, attack_type=attack_type)
            pw = PacketWithPrediction(packet=packet, prediction=prediction)
            ok = send_attack_alert(pw, provided_severity=severity, use_email=True)
            sent += 1 if ok else 0
        except Exception:
            continue

    print(f"Sent alerts for {sent} detected attacks (logged failures if any).")

if __name__ == "__main__":
    main()
