# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4lcyyBitaiLkyLADY4v4FxBu5uRB3-y
"""

!pip install shap xgboost pyarrow tensorflow --quiet

import numpy as np
import pandas as pd
import pickle

import matplotlib.pyplot as plt
import seaborn as sns

import shap
import tensorflow as tf

plt.style.use("default")
sns.set_style("whitegrid")

!ls

with open("final_model.pkl", "rb") as f:
    xgb_model = pickle.load(f)

with open("autoencoder_full.pkl", "rb") as f:
    ae_artifacts = pickle.load(f)

autoencoder = ae_artifacts["model"]
scaler = ae_artifacts["scaler"]
feature_columns = ae_artifacts["feature_columns"]

print("Models loaded successfully")
X_test = pd.read_parquet("X_test_selected.parquet")

print("X_test shape:", X_test.shape)
X_test.head()

X_shap = X_test.sample(5000, random_state=42)

explainer = shap.TreeExplainer(xgb_model)
shap_values = explainer.shap_values(X_shap)

# Global importance (multiclass-safe)
mean_shap = np.abs(shap_values).mean(axis=(0, 2))

shap_importance = pd.DataFrame({
    "feature": X_shap.columns,
    "importance": mean_shap
}).sort_values(by="importance", ascending=False)

top5_shap = shap_importance.head(5)
top5_shap

shap.summary_plot(
    shap_values,
    X_shap,
    plot_type="bar",
    max_display=5,
    show=True
)

sample_idx = 0

# FIX: choose class with max absolute SHAP contribution
pred_class = np.abs(shap_values[sample_idx]).mean(axis=0).argmax()

shap.force_plot(
    explainer.expected_value[pred_class],
    shap_values[sample_idx, :, pred_class],
    X_shap.iloc[sample_idx]
)

def compute_ae_feature_deviation(sample_df):
    x_scaled = scaler.transform(sample_df)
    x_reconstructed = autoencoder.predict(x_scaled, verbose=0)

    deviation = np.abs(x_scaled - x_reconstructed)[0]

    return pd.DataFrame({
        "feature": feature_columns,
        "deviation": deviation
    }).sort_values(by="deviation", ascending=False)
sample = X_test.iloc[[0]]

ae_deviation = compute_ae_feature_deviation(sample)
top5_ae = ae_deviation.head(5)

top5_ae

plt.figure(figsize=(10, 4))
plt.imshow(
    top5_ae["deviation"].values.reshape(1, -1),
    cmap="hot",
    aspect="auto"
)
plt.yticks([])
plt.xticks(
    range(len(top5_ae)),
    top5_ae["feature"],
    rotation=45,
    ha="right"
)
plt.colorbar(label="Reconstruction Error")
plt.title("Autoencoder Feature Deviation Heatmap")
plt.show()

def generate_explanation(shap_df, ae_df, attack_label):
    shap_features = ", ".join(shap_df["feature"].values[:2])
    ae_features = ", ".join(ae_df["feature"].values[:2])

    return (
        f"The network flow was classified as {attack_label} due to high influence "
        f"from features such as {shap_features}. "
        f"Additionally, abnormal behavior was detected in "
        f"{ae_features}, which deviated significantly from normal traffic patterns."
    )
attack_label = "DoS"  # example
explanation_text = generate_explanation(top5_shap, top5_ae, attack_label)

print(explanation_text)
