# -*- coding: utf-8 -*-
"""Copy of Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khHuv-pzxm0_I9lXDMIYEJwkSY9lQ_tT
"""



# Get Monday and Wednesday parquet values as monday_df and wednesday_df respectively
import pandas as pd

monday_df = pd.read_parquet("/content/Benign-Monday-no-metadata.parquet")
wednesday_df = pd.read_parquet("/content/DoS-Wednesday-no-metadata.parquet")

# Get first 100K values
monday_df.head(100000)

# To understand Datastructure
monday_df.info()

#Knowing the dimension of the dataframe
monday_df.shape

#checking for missing values
monday_df.isna().sum()

# to label each attack type
monday_df['Label'].value_counts()

# Number of rows before dropping duplicates
before = monday_df.shape[0]

# Drop duplicates
monday_df = monday_df.drop_duplicates()

# Number of rows after dropping duplicates
after = monday_df.shape[0]

# Number of duplicates dropped
print("Duplicates dropped:", before - after)

# Get first 100K values
wednesday_df.head(100000)

# To understand Datastructure
wednesday_df.info()

##Knowing the dimension of the dataframe
wednesday_df.shape

# checking for null values
wednesday_df.isna().sum()

# to label each attack type
wednesday_df['Label'].value_counts()

# Number of rows before dropping duplicates
before = wednesday_df.shape[0]

# Drop duplicates
wednesday_df= wednesday_df.drop_duplicates()

# Number of rows after dropping duplicates
after = wednesday_df.shape[0]

# Number of duplicates dropped
print("Duplicates dropped:", before - after)

# check made to make sure if the both files have same column name at the same position

monday_col_list = list(monday_df.columns.values)
wednesday_col_list = list(wednesday_df.columns.values)

mon_col_count = len(monday_col_list)
wed_col_count = len(wednesday_col_list)

print("Mon col count", mon_col_count)
print("Wed col count", wed_col_count)

matched_col_count = 0

# checking if both list have same number of columns
if wed_col_count == mon_col_count:

  # checking column names in both list with their index
  for i in range(wed_col_count):
    if wednesday_col_list[i] == monday_col_list[i]:
      matched_col_count += 1
else:
  print("column count not same")

"""
Check if the if both lists are identical, if yes,
Change column names of any one list in camelcase (i.e) all lowercase letters
with spaces replaced with underscore and store it as final_col_list
"""
final_col_list = []
identical = matched_col_count == wed_col_count and matched_col_count == mon_col_count
print("Both lists are identical:", identical)

if identical:
  final_col_list = monday_df.columns.str.replace(' ', '_').str.lower()
  print(final_col_list)

# concatenating monday_df and wednesday_df (row-wise)

if identical:
  df_combined = pd.concat([monday_df.head(100000),wednesday_df.head(100000)], ignore_index=True)

# To know the structure of dataset
df_combined.shape

# detailed information of the combined-dataset
df_combined.info()

# checking for the null values
df_combined.isna().sum()

df_combined.to_csv('/content/combined_200k.csv', index=False)

