# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HN5Aw7PTHM6FKchb5N7pqpqEdMGKWfkf
"""

import pandas as pd
import numpy as np
import pickle

from sklearn.metrics import classification_report, confusion_matrix, f1_score
import matplotlib.pyplot as plt
import seaborn as sns

# Load datasets
X_train_selected = pd.read_parquet("X_train_selected.parquet")
X_test_selected = pd.read_parquet("X_test_selected.parquet")

y_train = pd.read_parquet("y_train.parquet")["label"]
y_test = pd.read_parquet("y_test.parquet")["label"]

# Load artifacts
with open("labelencoder.pkl", "rb") as f:
    le = pickle.load(f)

print("Data loaded successfully")
print("Train shape:", X_train_selected.shape)
print("Test shape:", X_test_selected.shape)

def evaluate_model(model, X_test, y_test, model_name):
    y_pred = model.predict(X_test)

    print(f"\n===== {model_name} =====")
    print("Macro F1:", f1_score(y_test, y_pred, average="macro"))
    print("Weighted F1:", f1_score(y_test, y_pred, average="weighted"))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=le.classes_))

    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(10, 7))
    sns.heatmap(cm, annot=False, cmap="Blues",
                xticklabels=le.classes_,
                yticklabels=le.classes_)
    plt.title(f"{model_name} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

lr = LogisticRegression(
    solver="saga",
    multi_class="multinomial",
    max_iter=200,
    n_jobs=-1,
    class_weight="balanced",
    random_state=42
)

lr.fit(X_train_selected, y_train)

y_pred_lr = lr.predict(X_test_selected)

print("Logistic Regression Results")
print(classification_report(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=20,
    min_samples_split=10,
    min_samples_leaf=5,
    n_jobs=-1,
    class_weight="balanced",
    random_state=42
)

rf.fit(X_train_selected, y_train)

y_pred_rf = rf.predict(X_test_selected)

print("Random Forest Results")
print(classification_report(y_test, y_pred_rf))

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="multi:softprob",
    num_class=len(y_train.unique()),
    tree_method="hist",
    eval_metric="mlogloss",
    n_jobs=-1,
    random_state=42
)

xgb.fit(X_train_selected, y_train)

y_pred_xgb = xgb.predict(X_test_selected)

print("XGBoost Results")
print(classification_report(y_test, y_pred_xgb))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

def plot_confusion(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=False, cmap="Blues", fmt="d")
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

plot_confusion(y_test, y_pred_xgb, "XGBoost Confusion Matrix")

from sklearn.metrics import f1_score, classification_report

# Collect predictions
predictions = {
    "Logistic Regression": y_pred_lr,
    "Random Forest": y_pred_rf,
    "XGBoost": y_pred_xgb
}

# Evaluate F1-score (macro-average for multi-class)
f1_scores = {}
for name, y_pred in predictions.items():
    f1 = f1_score(y_test, y_pred, average="macro")
    f1_scores[name] = f1
    print(f"--- {name} ---")
    print(classification_report(y_test, y_pred))

# Select best model
best_model_name = max(f1_scores, key=f1_scores.get)
print(f"\n Best model based on F1-score: {best_model_name}")

# Map model name to trained object
models = {
    "Logistic Regression": lr,
    "Random Forest": rf,
    "XGBoost": xgb
}
best_model = models[best_model_name]

# Save the final model
import pickle
with open("final_model.pkl", "wb") as f:
    pickle.dump(best_model, f)

print(f"Final model saved: {best_model_name}")